kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mittwald:replicator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets", "configmaps"]
  verbs: ["get", "watch", "list", "update", "patch"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: replicator
  namespace: kube-system